export const REQUEST_RECIPES_SUCCESS = 'REQUEST_RECIPES_SUCCESS';
export const REQUEST_RECIPES_ERROR = 'REQUEST_RECIPES_ERROR';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const GET_RECIPE_BY_ID = 'GET_RECIPE_BY_ID';
export const DELETE_RECIPE = 'DELETE_RECIPE';
